version: 2

jobs:
  build:
    #working_directory: /go/src/github.com/isindir/circleci-kind-sandbox
    docker:
      - image: circleci/golang:1.12.7-stretch
    steps:
      - checkout
      - run:
          name: Install kind
          command: |
            GO111MODULE="on" go get sigs.k8s.io/kind@v0.4.0
      - setup_remote_docker:
          version: 18.09.3
          docker_layer_caching: true
